services:
  postgres:
    image: postgres:17-alpine
    container_name: selora-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: selora_shop
      POSTGRES_USER: selora
      POSTGRES_PASSWORD: strong_password_123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./selora-backend
    container_name: selora-backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    environment:
      DEBUG: "True"

      BASE_URL: "api/"
      ADMIN_URL: "admin/"
      SECRET_KEY: "docker-secret-key"

      LANGUAGE_CODE: "en-us"
      TIME_ZONE: "Asia/Tehran"
      USE_I18N: "False"
      USE_TZ: "True"

      ACCESS_TOKEN_LIFETIME: "60"
      REFRESH_TOKEN_LIFETIME: "7"

      USE_SQLITE: "False"

      DB_NAME: "selora_shop"
      DB_USER: "selora"
      DB_PASSWORD: "strong_password_123"
      DB_HOST: "postgres"
      DB_PORT: "5432"

      INTERNAL_IPS: "localhost,127.0.0.1,172.18.0.1"

      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"

      CORS_ALLOW_CREDENTIALS: "True"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
      CSRF_TRUSTED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"

      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_PASSWORD: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"

    volumes:
      - ./selora-backend:/app

    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py seed_data &&
        python manage.py create_superuser &&
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    build:
      context: ./selora-frontend
    container_name: selora-frontend

    depends_on:
      - backend

    ports:
      - "3000:3000"

    environment:
      BASE_API_URL: "http://backend:8000/api/v1/"
      NEXT_PUBLIC_BASE_API_URL: "http://127.0.0.1:8000/api/v1/"
      CHOKIDAR_USEPOLLING: "true"

    volumes:
      - ./selora-frontend:/app
      - /app/node_modules

volumes:
  postgres_data: