# Generated by Django 6.0.7 on 2026-07-30 12:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_productvariantmodel_variantimagemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.productvariantmodel')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cartmodel')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cartmodel',
            index=models.Index(fields=['created_at'], name='cart_cartmo_created_3fc9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='cartmodel',
            index=models.Index(fields=['updated_at'], name='cart_cartmo_updated_bed58a_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitemmodel',
            index=models.Index(fields=['cart'], name='cart_cartit_cart_id_097506_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitemmodel',
            index=models.Index(fields=['variant'], name='cart_cartit_variant_3a7e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitemmodel',
            index=models.Index(fields=['added_at'], name='cart_cartit_added_a_072ad1_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitemmodel',
            constraint=models.UniqueConstraint(fields=('cart', 'variant'), name='unique_cart_variant'),
        ),
    ]
