# Generated by Django 6.0.7 on 2026-07-29 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="IP address of the user's device.", null=True)),
                ('user_agent', models.TextField(blank=True, help_text="User agent of the user's device.", null=True)),
                ('device', models.CharField(blank=True, help_text="Device type of the user's device.", max_length=255, null=True)),
                ('browser', models.CharField(blank=True, help_text="Browser of the user's device.", max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, help_text="Operating system of the user's device.", max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text="Country of the user's device.", max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text="City of the user's device.", max_length=100, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('failure_reason', models.TextField(blank=True, help_text="Failure reason of the user's device.", null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'db_table': 'login_histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
